"""Minimal DeepSeek Harness (dsh) ACP profile for the trading decision worker.

The stock ``acp`` profile boots the full coding-agent surface: two dozen
model-facing tool schemas, the workspace instruction loader, the skill
catalog, slash commands, goal/plan tooling and the runtime-context
boilerplate.  All of it is re-sent on every model request, while the trading
decision prompt explicitly forbids tool use.  Measured on a live decision
round, that fixed overhead costs roughly 19 KB of prompt bytes per request
(24 tool schemas at ~18.5 KB plus ~21.9 KB of runtime/skill context on the
first request of a session) before any market data is included.

This module owns a profile overlay that removes exactly that surface.  It
changes no trading semantics: the observation set, entry gates, prompt,
schema, validation and order path are untouched.  Only the coding-agent
scaffolding a schema-constrained JSON decision never uses is disabled.
"""

from __future__ import annotations

from hashlib import sha256
import os
from pathlib import Path
from typing import Mapping

# ``dsh`` boots ``$DSH_HOME/profiles/<name>``.  The overlay is injected with
# ``--patch`` so no profile directory has to exist or be written.
PROFILE_NAME = "novatrade-decision"
PROFILE_DIRECTORY_NAME = "novatrade-deepseek"

# Selecting this profile requires the launcher flags below; an operator can
# set ``NOVATRADE_DEEPSEEK_PROFILE=0`` (or ``off``/``none``/``stock``) to go
# back to the vendor profile without a code change.
DISABLED_VALUES = frozenset({"0", "off", "none", "stock", "disabled"})
PROFILE_ENV = "NOVATRADE_DEEPSEEK_PROFILE"

# Bundle rows that exist in @deepseek-ai/dsh-base or @deepseek-ai/dsh-acp-app.
# Every id below is tooling for an autonomous coding agent: it either adds a
# model-facing tool schema (re-sent on each request) or injects a prompt
# section the decision contract never reads.
_DISABLED_ROWS = (
    # Model-facing tool schemas.
    "tool-bash",
    "tool-pwsh",
    "tool-jobs",
    "tool-fs",
    "tool-fs-search",
    "tool-skill",
    "tool-subagent",
    "tool-subagent-fork",
    "tool-subagent-control",
    "tool-subagent-list-agents",
    "tool-workflow",
    "tool-web",
    "tool-todo",
    "tool-goal",
    "tool-ralph",
    # Prompt sections that are not part of the decision contract.
    "skill",
    "skill-filesystem",
    "agent-instructions",
    "commands",
    "command-feedback",
    "command-goal",
    "command-compact",
    "plan-mode",
    "goal",
    "goal-round-driver",
    "repeat-tool-reminder",
    # Conversation compaction.  Every decision runs in a fresh ACP session
    # with a single prompt, so there is no history to compact.
    "compaction-basic",
    "tool-result-pruner",
)

# The persona mirrors the vendor ``acp`` profile (``You are a coding agent
# powered by the {{model}} model.``) with the harness's own runtime context
# removed, so the model still knows it is an agent answering one request.
_PERSONA_PREFIX = (
    "You are an automated agent powered by the {{model}} model, answering a "
    "single machine request. Return only what that request asks for."
)

def _render_patch() -> str:
    lines = [
        "# Generated by NovaTrade backend/deepseek_profile.py. Do not edit;",
        "# the trading worker rewrites this overlay from its bundled template.",
        "#",
        "# A prompt-only decision profile: no model-facing tools, no workspace",
        "# instructions, no skill catalog, no runtime-context boilerplate. Every",
        "# row below is re-sent on each request, and the constrained JSON",
        "# decision contract uses none of them.",
        "",
    ]
    for row_id in _DISABLED_ROWS:
        lines.append(f"- id: {row_id}")
        lines.append("  disabled: true")
    lines.extend(
        [
            "",
            "- id: system-prompt",
            "  config:",
            "    includeHarnessIdentity: false",
            "    includeRuntimeContext: false",
            "    personaPrefix: >-",
            f"      {_PERSONA_PREFIX}",
            "",
        ]
    )
    return "\n".join(lines)


PATCH_YAML = _render_patch()

# Keep the tuple order stable for readers of the file and for tests.
DISABLED_ROWS = tuple(_DISABLED_ROWS)


def _profile_enabled(env: Mapping[str, str] | None = None) -> bool:
    environment = os.environ if env is None else env
    value = (environment.get(PROFILE_ENV) or "").strip().lower()
    return value not in DISABLED_VALUES


def dsh_home(env: Mapping[str, str] | None = None) -> Path:
    """Resolve ``$DSH_HOME`` the way the dsh launcher resolves it."""
    environment = os.environ if env is None else env
    configured = (environment.get("DSH_HOME") or "").strip()
    if configured:
        return Path(configured).expanduser()
    return Path.home() / ".dsh"


def patch_path(
    home: Path | None = None, env: Mapping[str, str] | None = None,
) -> Path:
    """Return the stable, content-addressed overlay path for this template."""
    base = Path(home) if home is not None else dsh_home(env)
    digest = sha256(PATCH_YAML.encode("utf-8")).hexdigest()[:16]
    return base / PROFILE_DIRECTORY_NAME / f"{PROFILE_NAME}-{digest}.yml"


def ensure_patch_file(
    home: Path | None = None, env: Mapping[str, str] | None = None,
) -> Path | None:
    """Materialize the overlay and return its path, or None when unavailable.

    A missing or unwritable home is not fatal: the caller falls back to the
    vendor profile instead of blocking trading decisions.
    """
    if not _profile_enabled(env):
        return None
    try:
        path = patch_path(home, env)
        desired = PATCH_YAML.encode("utf-8")
        try:
            if path.read_bytes() == desired:
                return path
        except OSError:
            pass
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(path.name + ".tmp")
        temporary.write_bytes(desired)
        temporary.replace(path)
        return path
    except OSError:
        return None


def launcher_arguments(
    patch: Path | None,
) -> list[str]:
    """Return the launcher-flag suffix for one dsh ACP invocation."""
    if patch is None:
        # ``dsh`` without a profile only prints usage. ``acp`` is the
        # installed vendor profile; the overlay is an optional patch on top
        # of it, not a dynamically registered profile name.
        return ["--profile", "acp"]
    return ["--profile", "acp", "--patch", str(patch)]


__all__ = [
    "DISABLED_ROWS",
    "PATCH_YAML",
    "PROFILE_ENV",
    "PROFILE_NAME",
    "dsh_home",
    "ensure_patch_file",
    "launcher_arguments",
    "patch_path",
]
